name: Deploy (production)
on:
  workflow_run:
    workflows: ["Tests & Build"]
    types:
      - completed
    branches:
      - 'prod'
jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: 'cd ../../var/www/dogger && sh ./server_deploy.sh ${{ secrets.SSH_PASSWORD }}'
